### ISSUE TITLE
Text Editor doesn't work

### ISSUE THREAD

**Issue by ZaidQureshi** [zagortenay333/cronomix#144]
I am using Gnome 3.38 and just installed time++ as it seems really cool.
However, when I click "Add New Task" or click the pencil on some existing tasks it doesn't do anything.
The text editor doesn't launch.
Are there some pre-requisites that I need to make the editor work?
Thanks

**Comment by zagortenay333** [comment]
Sorry about that. Should be fixed now.

**Comment by XanderLeaDaren** [comment]
Hello, I still have the same issue.

Debian sid, Gnome 3.38.1

Any recommended steps to help solve the problem?

**Comment by zagortenay333** [comment]
Are you using the github version?

**Comment by XanderLeaDaren** [comment]
Oops, sorry, I was using the version at extensions.gnome.org, thinking it was the latest.

I just installed the github version, working perfectly fine. Thanks a lot for the app you developed, by the way: everything I need is in it! 👍🏽

**Comment by zagortenay333** [comment]
Yeah they haven't reviewed it yet: https://extensions.gnome.org/review/

Cheers
