### ISSUE TITLE
Stopwatch bugs the countdown [BUG]

### ISSUE THREAD

**Issue by yuritoledo** [zagortenay333/cronomix#60]
Hello :D

Your extension is amazing!
I've found a bug, I don't know if you did know about it.
I start the SW, after some time (sec, min, whatever) I stop the SW and lock the screen. When I get back and start de SW, it start another countdown, from another time.
If I stop it in 01:11:56 > Pause it > Block the gnome > back > start > SW is in 00:45 (for exemple)

**Comment by zagortenay333** [comment]
Are you using the github version?

**Comment by yuritoledo** [comment]
Wow so fast! haha

No, the gnome extension site version.

Should I use the github version?

**Comment by yuritoledo** [comment]
Github version installed and the bug was fixed!!

**Comment by zagortenay333** [comment]
Even the version that I uploaded last year (December) has still not been reviewed on that site..
